// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxmfcfainsxikfwhinat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bWZjZmFpbnN4aWtmd2hpbmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTg5NzEsImV4cCI6MjA2NTU5NDk3MX0.71SA-iOzqKZ_18hLbaRCnIrF2GgzY9Gz27iqUbBwKr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);